name: SNPT Transactions Report

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # JST 0:00, 6:00, 12:00, 18:00 に実行（UTC 15:00, 21:00, 3:00, 9:00）
  workflow_dispatch:  # 手動実行可能

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run transaction summary
        env:
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python snpt_summary.py
name: Daily SNPT Report

on:
  schedule:
    - cron: '0 15 * * *'  # JST 0:00（UTC 15:00）
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-daily-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run daily report script
        env:
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python daily_report.py




