name: SNPT Transactions Summary

on:
  schedule:
    - cron: '0 15,21,3,9 * * *'  # JST 0:00, 6:00, 12:00, 18:00 (UTC 15:00, 21:00, 3:00, 9:00)
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SNPT summary script
        env:
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python snpt_summary.py
